### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by MoonlightSystem** [kill05/equivalentexchange-bta#1]
Not sure what caused this in EE-BTA, but thought you might want to know!
Modslist:
![image](https://github.com/kill05/equivalentexchange-bta/assets/8211402/ad0578e2-c1fc-49ed-85b7-35c29fb188ee)

```
Minecraft ran into an unexpected problem!

To prevent more problems, the current game has quit, but you can try to keep playing.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 6/28/24, 1:52 PM

Minecraft: Better than Adventure! 7.2 Prerelease 2
OS: Windows 11 (amd64) version 10.0
Java: 17.0.10, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4
OpenGL: NVIDIA GeForce RTX 2050/PCIe/SSE2 version 4.6.0 NVIDIA 555.99, NVIDIA Corporation

java.lang.IllegalArgumentException: invalid meta: -1
    at com.github.kill05.equivalentexchange.emc.EmcKey.<init>(EmcKey.java:15)
    at com.github.kill05.equivalentexchange.emc.EmcKey.<init>(EmcKey.java:25)
    at com.github.kill05.equivalentexchange.emc.EmcRegistry.getEmcValue(EmcRegistry.java:275)
    at com.github.kill05.equivalentexchange.emc.EmcRegistry.computeRecipeCostAndRegister(EmcRegistry.java:210)
    at com.github.kill05.equivalentexchange.emc.EmcRegistry.computeRecipeCosts(EmcRegistry.java:137)
    at com.github.kill05.equivalentexchange.emc.EmcRegistry.reloadValues(EmcRegistry.java:58)
    at com.github.kill05.equivalentexchange.EquivalentExchange.afterGameStart(EquivalentExchange.java:86)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at net.minecraft.client.Minecraft.handler$zcj000$halplibe$afterGameStartEntrypoint(Minecraft.java:4042)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:530)
    at net.minecraft.client.Minecraft.run(Minecraft.java:785)
    at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by kill05** [comment]
Thanks, will be fixed in the next update
